baseURL = 'https://clojure-phrasebook.composed.ch'
languageCode = 'en-us'
title = 'Clojure Phrasebook'

[minify]
minifyOutput = true

[params]
openapi = false
showVisitedLinks = true
themeVariant = 'blue'

[params.author]
name = 'Patrick Bucher, Composed GmbH'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'
